# Generated by Django 4.1.3 on 2023-02-15 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, choices=[('Macbook', 'Macbook'), ('IPad', 'Ipad'), ('Iphone', 'Iphone'), ('Watch', 'Watch')], max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('img', models.ImageField(upload_to='image/')),
                ('color', models.CharField(blank=True, choices=[('WHITE', 'White'), ('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BLACK', 'Black'), ('PURPLE', 'Purple')], max_length=60)),
                ('xotira', models.CharField(blank=True, choices=[('128', '128'), ('256', '256'), ('512', '512'), ('1TB', '1Tb')], max_length=60)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap.author')),
            ],
        ),
    ]
