# Generated by Django 4.1.3 on 2023-02-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='xotira',
        ),
        migrations.AddField(
            model_name='blog',
            name='size',
            field=models.CharField(blank=True, choices=[('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44')], max_length=60),
        ),
        migrations.AlterField(
            model_name='author',
            name='name1',
            field=models.CharField(blank=True, choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Gucci', 'Gucci')], max_length=60),
        ),
        migrations.AlterField(
            model_name='blog',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('RED', 'Red')], max_length=60),
        ),
    ]
