# Generated by Django 4.1.3 on 2023-02-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap', '0002_remove_blog_xotira_blog_size_alter_author_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='color',
            field=models.CharField(blank=True, choices=[('WHITE', 'White'), ('BLACK', 'Black'), ('BLUE', 'Blue'), ('White_and_Black', 'White And Black')], max_length=60),
        ),
    ]
